<a href="https://colab.research.google.com/github/nitinsaimajji/DSA-/blob/main/Untitled4.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [2]:
df=pd.read_csv("diamond.csv")

In [3]:
df

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
4       0.31       Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53935   0.72      Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53936   0.72       Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56
53938   0.86    Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75      Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[53940 rows x 10 columns]

In [4]:
## 2. Write a program to filter the DataFrame rows to only show carat weight at least 0.3

In [19]:
df1=df.loc[df['carat']<=0.3]
df1

       carat        cut color clarity  depth  table  price     x     y     z
0       0.23      Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21    Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
2       0.23       Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
3       0.29    Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53635   0.30      Ideal     I    VVS1   62.1   56.0    552  4.30  4.33  2.68
53636   0.30      Ideal     D     SI1   61.6   57.0    552  4.28  4.32  2.65
53637   0.30  Very Good     D     SI1   62.5   57.0    552  4.26  4.28  2.67
53638   0.30      Ideal     D     SI1   61.0   57.0    552  4.29  4.33  2.63
53639   0.30      Ideal     D     SI1   61.0   56.0    552  4.35  4.37  2.66

[4203 rows x 10 columns]

In [8]:
## 3. find the diamonds that are either Premium or Ideal

In [15]:
df1 = df[(df['cut'] == 'Premium') | (df['cut']=='Ideal')]
df1

       carat      cut color clarity  depth  table  price     x     y     z
0       0.23    Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
11      0.23    Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53935   0.72    Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74
53939   0.75    Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[35342 rows x 10 columns]

In [16]:
## 4 . calculate the mean of each numeric column of diamonds DataFrame

In [47]:

cols=['carat','depth','price','table','x','y','z']

for i in cols:
  print(df[i].mean())

0.7979397478680014
61.749404894327036
3932.799721913237
57.45718390804598
5.731157211716722
5.734525954764553
3.5387337782721544

In [48]:
## 6. calculate count, minimum, maximum price for each cut of diamonds DataFrame

In [63]:
groupby=df.groupby('cut')
for carat,group in groupby:
    print(carat,group)

Fair        carat   cut color clarity  depth  table  price     x     y     z
8       0.22  Fair     E     VS2   65.1   61.0    337  3.87  3.78  2.49
91      0.86  Fair     E     SI2   55.1   69.0   2757  6.45  6.33  3.52
97      0.96  Fair     F     SI2   66.3   62.0   2759  6.27  5.95  4.07
123     0.70  Fair     F     VS2   64.5   57.0   2762  5.57  5.53  3.58
124     0.70  Fair     F     VS2   65.3   55.0   2762  5.63  5.58  3.66
...      ...   ...   ...     ...    ...    ...    ...   ...   ...   ...
53757   0.72  Fair     F     VS2   55.4   64.0   2724  6.06  5.97  3.34
53800   0.90  Fair     I     VS1   68.7   62.0   2732  5.83  5.79  3.99
53863   1.00  Fair     I     SI2   66.8   56.0   2743  6.22  6.12  4.13
53879   1.04  Fair     G     SI2   65.2   57.0   2745  6.25  6.23  4.07
53882   0.71  Fair     D     VS1   65.4   59.0   2747  5.62  5.58  3.66

[1610 rows x 10 columns]
Good        carat   cut color clarity  depth  table  price     x     y     z
2       0.23  Good     E     VS1   56.9   65.0    327  4.05  4.07  2.31
4       0.31  Good     J     SI2   63.3   58.0    335  4.34  4.35  2.75
10      0.30  Good     J     SI1   64.0   55.0    339  4.25  4.28  2.73
17      0.30  Good     J     SI1   63.4   54.0    351  4.23  4.29  2.70
18      0.30  Good     J     SI1   63.8   56.0    351  4.23  4.26  2.71
...      ...   ...   ...     ...    ...    ...    ...   ...   ...   ...
53913   0.80  Good     G     VS2   64.2   58.0   2753  5.84  5.81  3.74
53914   0.84  Good     I     VS1   63.7   59.0   2753  5.94  5.90  3.77
53916   0.74  Good     D     SI1   63.1   59.0   2753  5.71  5.74  3.61
53927   0.79  Good     F     SI1   58.1   59.0   2756  6.06  6.13  3.54
53936   0.72  Good     D     SI1   63.1   55.0   2757  5.69  5.75  3.61

[4906 rows x 10 columns]
Ideal        carat    cut color clarity  depth  table  price     x     y     z
0       0.23  Ideal     E     SI2   61.5   55.0    326  3.95  3.98  2.43
11      0.23  Ideal     J     VS1   62.8   56.0    340  3.93  3.90  2.46
13      0.31  Ideal     J     SI2   62.2   54.0    344  4.35  4.37  2.71
16      0.30  Ideal     I     SI2   62.0   54.0    348  4.31  4.34  2.68
39      0.33  Ideal     I     SI2   61.8   55.0    403  4.49  4.51  2.78
...      ...    ...   ...     ...    ...    ...    ...   ...   ...   ...
53925   0.79  Ideal     I     SI1   61.6   56.0   2756  5.95  5.97  3.67
53926   0.71  Ideal     E     SI1   61.9   56.0   2756  5.71  5.73  3.54
53929   0.71  Ideal     G     VS1   61.4   56.0   2756  5.76  5.73  3.53
53935   0.72  Ideal     D     SI1   60.8   57.0   2757  5.75  5.76  3.50
53939   0.75  Ideal     D     SI2   62.2   55.0   2757  5.83  5.87  3.64

[21551 rows x 10 columns]
Premium        carat      cut color clarity  depth  table  price     x     y     z
1       0.21  Premium     E     SI1   59.8   61.0    326  3.89  3.84  2.31
3       0.29  Premium     I     VS2   62.4   58.0    334  4.20  4.23  2.63
12      0.22  Premium     F     SI1   60.4   61.0    342  3.88  3.84  2.33
14      0.20  Premium     E     SI2   60.2   62.0    345  3.79  3.75  2.27
15      0.32  Premium     E      I1   60.9   58.0    345  4.38  4.42  2.68
...      ...      ...   ...     ...    ...    ...    ...   ...   ...   ...
53928   0.79  Premium     E     SI2   61.4   58.0   2756  6.03  5.96  3.68
53930   0.71  Premium     E     SI1   60.5   55.0   2756  5.79  5.74  3.49
53931   0.71  Premium     F     SI1   59.8   62.0   2756  5.74  5.73  3.43
53934   0.72  Premium     D     SI1   62.7   59.0   2757  5.69  5.73  3.58
53938   0.86  Premium     H     SI2   61.0   58.0   2757  6.15  6.12  3.74

[13791 rows x 10 columns]
Very Good        carat        cut color clarity  depth  table  price     x     y     z
5       0.24  Very Good     J    VVS2   62.8   57.0    336  3.94  3.96  2.48
6       0.24  Very Good     I    VVS1   62.3   57.0    336  3.95  3.98  2.47
7       0.26  Very Good     H     SI1   61.9   55.0    337  4.07  4.11  2.53
9       0.23  Very Good     H     VS1   59.4   61.0    338  4.00  4.05  2.39
19      0.30  Very Good     J     SI1   62.7   59.0    351  4.21  4.27  2.66
...      ...        ...   ...     ...    ...    ...    ...   ...   ...   ...
53921   0.70  Very Good     E     VS2   62.8   60.0   2755  5.59  5.65  3.53
53922   0.70  Very Good     D     VS1   63.1   59.0   2755  5.67  5.58  3.55
53932   0.70  Very Good     E     VS2   60.5   59.0   2757  5.71  5.76  3.47
53933   0.70  Very Good     E     VS2   61.2   59.0   2757  5.69  5.72  3.49
53937   0.70  Very Good     D     SI1   62.8   60.0   2757  5.66  5.68  3.56

[12082 rows x 10 columns]